name: build-libvips
on: push
jobs:
  linux:
    name: Linux build
    runs-on: ubuntu-latest-18.04
    steps:
    - name: Requirements
      run: apt-get install -y --no-install-recommends \
        apt-utils \
        automake \
        build-essential \
        ca-certificates \
        cmake \
        curl \
        debconf \
        debhelper \
        dpkg \
        git \
        gnupg \
        gobject-introspection \
        libexpat1-dev \
        libglib2.0-dev \
        mc \
        pkg-config \
        software-properties-common \
        sudo \
        wget
    - name: Build
      run: libvips/build.sh
