name: build-libvips
env:
  libvipsVersion: '8.10.5'

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install requirements
        run: |
          sudo apt-get install -y --no-install-recommends \
            gnupg
      - name: Copy dist
        run: |
          cp td-libvips-dev-dist/* ppa
          ls -lah ppa
      - name: Reindex
        working-directory: ppa
        run: |
          EMAIL=maxim.oransky@gmail.com

          # Packages & Packages.gz
          dpkg-scanpackages --multiversion . > Packages
          gzip -k -f Packages

          apt-ftparchive release . > Release
          gpg --default-key "${EMAIL}" -abs -o - Release > Release.gpg
          gpg --default-key "${EMAIL}" --clearsign -o - Release > InRelease
      - name: Push
        uses: github-actions-x/commit@v2.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'main'
          commit-message: 'publish'
          force-add: 'true'
