name: build-libvips

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Install requirements
        run: apt-get install -y --no-install-recommends apt-utils
#          automake \
#          build-essential \
#          ca-certificates \
#          cmake \
#          curl \
#          debconf \
#          debhelper \
#          dpkg \
#          git \
#          gnupg \
#          gobject-introspection \
#          libexpat1-dev \
#          libglib2.0-dev \
#          mc \
#          pkg-config \
#          software-properties-common \
#          sudo \
#          wget
