# based on https://assafmo.github.io/2019/05/02/ppa-repo-hosted-on-github.html
name: build
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install requirements
        run: |
          sudo apt-get install -y --no-install-recommends \
            gnupg
      - name: Copy dist
        run: |
          cp td-libvips-dev-dist/* ppa
          ls -lah ppa
      - name: Import gpg key
        run: |
          base64 -d <<< "${{ secrets.GPG_PRIVATE_KEY }}" > my-private-key.asc
          gpg --import my-private-key.asc
      - name: Packages file
        working-directory: ppa
        run: |
          dpkg-scanpackages --multiversion . > Packages
          gzip -k -f Packages
      - name: Release file
        working-directory: ppa
        run: |
          apt-ftparchive release . > Release
          gpg --default-key "${{ secrets.GPG_EMAIL }}" -abs -o - Release > Release.gpg
          gpg --default-key "${{ secrets.GPG_EMAIL }}" --clearsign -o - Release > InRelease
      - name: Publish
        uses: github-actions-x/commit@v2.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'main'
          commit-message: 'publish'
          force-add: 'true'
